// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaL4uGTxohA3v9s55f4GSGrFQMK_VjMwo',
    appId: '1:596591913554:android:a33c8ac26120e54abd4d8b',
    messagingSenderId: '596591913554',
    projectId: 'messmate-8e224',
    storageBucket: 'messmate-8e224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_-ZbWS0G3QhJDTOFe6_1kp38v4OH0QQ',
    appId: '1:596591913554:ios:5dbe94d1822c32cebd4d8b',
    messagingSenderId: '596591913554',
    projectId: 'messmate-8e224',
    storageBucket: 'messmate-8e224.firebasestorage.app',
    iosBundleId: 'com.example.messmateUser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgUozbFV87_w1MYDrVoB2tjyVko4SWK0',
    appId: '1:596591913554:web:e6d8f706831a2258bd4d8b',
    messagingSenderId: '596591913554',
    projectId: 'messmate-8e224',
    authDomain: 'messmate-8e224.firebaseapp.com',
    storageBucket: 'messmate-8e224.firebasestorage.app',
  );

}